"""Compare token columns between original CSV and tokenized CSV.

Example:
    python scripts/compare_tokens.py --original data/raw/pii_dataset.csv --tokenized data/processed/tokenized.csv

If your original file is pii_text.csv and it does not have a tokens column, use pii_dataset.csv
as the original reference file.
"""

from __future__ import annotations

import argparse
import ast
import csv
import json
from pathlib import Path
from typing import Any


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Compare token columns from two CSV files.")
    parser.add_argument(
        "--original",
        required=True,
        help="Path to original CSV file that contains the reference tokens column.",
    )
    parser.add_argument(
        "--tokenized",
        required=True,
        help="Path to tokenized CSV file generated by tokenizer.",
    )
    parser.add_argument(
        "--original-token-col",
        default="tokens",
        help="Token column name in original CSV. Default: tokens.",
    )
    parser.add_argument(
        "--tokenized-token-col",
        default="tokens",
        help="Token column name in tokenized CSV. Default: tokens.",
    )
    parser.add_argument(
        "--id-col",
        default="document",
        help="ID column used to align rows. Default: document.",
    )
    parser.add_argument(
        "--max-show",
        type=int,
        default=20,
        help="Maximum number of mismatched rows to print. Default: 20.",
    )
    return parser.parse_args()


def parse_token_cell(value: Any) -> list[str]:
    """Parse a token cell from CSV into list[str]."""
    if value is None:
        return []

    if isinstance(value, list):
        return [str(item) for item in value]

    text = str(value).strip()

    if text == "":
        return []

    # Common format in CSV: "['My', 'name', 'is']"
    try:
        parsed = ast.literal_eval(text)
        if isinstance(parsed, list):
            return [str(item) for item in parsed]
    except (SyntaxError, ValueError):
        pass

    # JSON format: ["My", "name", "is"]
    try:
        parsed = json.loads(text)
        if isinstance(parsed, list):
            return [str(item) for item in parsed]
    except json.JSONDecodeError:
        pass

    # Fallback for simple whitespace-separated strings.
    return text.split()


def load_rows_by_id(path: str | Path, id_col: str) -> dict[str, dict[str, str]]:
    with open(path, "r", encoding="utf-8", newline="") as file:
        reader = csv.DictReader(file)
        if reader.fieldnames is None:
            raise ValueError(f"File has no header: {path}")

        if id_col not in reader.fieldnames:
            raise ValueError(
                f"Column '{id_col}' not found in {path}. "
                f"Available columns: {reader.fieldnames}"
            )

        rows: dict[str, dict[str, str]] = {}
        for index, row in enumerate(reader, start=1):
            row_id = str(row.get(id_col, "")).strip()
            if row_id == "":
                row_id = str(index)
            rows[row_id] = row

    return rows


def first_difference(tokens_a: list[str], tokens_b: list[str]) -> tuple[int, str | None, str | None] | None:
    max_len = max(len(tokens_a), len(tokens_b))

    for index in range(max_len):
        token_a = tokens_a[index] if index < len(tokens_a) else None
        token_b = tokens_b[index] if index < len(tokens_b) else None

        if token_a != token_b:
            return index, token_a, token_b

    return None


def main() -> None:
    args = parse_args()

    original_rows = load_rows_by_id(args.original, args.id_col)
    tokenized_rows = load_rows_by_id(args.tokenized, args.id_col)

    common_ids = sorted(set(original_rows) & set(tokenized_rows), key=lambda x: int(x) if x.isdigit() else x)
    missing_in_tokenized = sorted(set(original_rows) - set(tokenized_rows))
    extra_in_tokenized = sorted(set(tokenized_rows) - set(original_rows))

    if not common_ids:
        raise ValueError("No matching document IDs between the two files.")

    total = len(common_ids)
    matched = 0
    mismatches: list[dict[str, Any]] = []

    for row_id in common_ids:
        original_row = original_rows[row_id]
        tokenized_row = tokenized_rows[row_id]

        if args.original_token_col not in original_row:
            raise ValueError(
                f"Column '{args.original_token_col}' not found in original file. "
                f"Available columns: {list(original_row.keys())}"
            )

        if args.tokenized_token_col not in tokenized_row:
            raise ValueError(
                f"Column '{args.tokenized_token_col}' not found in tokenized file. "
                f"Available columns: {list(tokenized_row.keys())}"
            )

        original_tokens = parse_token_cell(original_row[args.original_token_col])
        tokenized_tokens = parse_token_cell(tokenized_row[args.tokenized_token_col])

        if original_tokens == tokenized_tokens:
            matched += 1
        else:
            diff = first_difference(original_tokens, tokenized_tokens)
            mismatches.append(
                {
                    "id": row_id,
                    "original_len": len(original_tokens),
                    "tokenized_len": len(tokenized_tokens),
                    "diff": diff,
                    "original_tokens": original_tokens,
                    "tokenized_tokens": tokenized_tokens,
                }
            )

    different = total - matched
    match_percent = matched / total * 100
    diff_percent = different / total * 100

    print("=" * 70)
    print("TOKEN COMPARISON RESULT")
    print("=" * 70)
    print(f"Original file : {args.original}")
    print(f"Tokenized file: {args.tokenized}")
    print(f"Rows compared : {total}")
    print(f"Matched rows  : {matched} ({match_percent:.2f}%)")
    print(f"Different rows: {different} ({diff_percent:.2f}%)")

    if missing_in_tokenized:
        print(f"Missing IDs in tokenized file: {len(missing_in_tokenized)}")
        print("Example:", missing_in_tokenized[:10])

    if extra_in_tokenized:
        print(f"Extra IDs in tokenized file: {len(extra_in_tokenized)}")
        print("Example:", extra_in_tokenized[:10])

    if not mismatches:
        print("\nResult: PASS - All token columns are identical.")
        return

    print("\nResult: FAIL - Some token columns are different.")
    print(f"\nShowing first {min(args.max_show, len(mismatches))} mismatch(es):")

    for item in mismatches[: args.max_show]:
        diff = item["diff"]
        print("-" * 70)
        print(f"Document ID   : {item['id']}")
        print(f"Original len  : {item['original_len']}")
        print(f"Tokenized len : {item['tokenized_len']}")

        if diff is not None:
            index, original_token, tokenized_token = diff
            print(f"First diff at token index: {index}")
            print(f"Original token : {original_token!r}")
            print(f"Tokenized token: {tokenized_token!r}")

            start = max(0, index - 5)
            end = index + 6

            print("Original context :")
            print(item["original_tokens"][start:end])

            print("Tokenized context:")
            print(item["tokenized_tokens"][start:end])


if __name__ == "__main__":
    main()
